### ISSUE TITLE
IMM Review

### ISSUE THREAD

**Issue by idg10** [corvus-dotnet/Corvus.Monitoring#32]
Go through every item on the IP Maturity Matrix and ensure it is up to date

- [x] **Shared Engineering Standards**
- [x] **Coding Standards**
- [x] **Executable Specifications**: correct, but could be improved with #27
- [x] **Code Coverage**: at over 97%
- [x] **Benchmarks**: score correct, could be improved with #28
- [x] **Reference Documentation**: score correct, could be improved with #29
- [x] **Design & Implementation Documentation**: score correct, could be improved with #4 #30
- [x] **How-to Documentation**: score correct, could be improved with #31 
- [x] **Date of Last IP Review**: update score once this review is complete
- [x] **Framework Version**: update score once this review is complete
- [x] **Associated Work Items**: need roadmap #48
- [x] **Source Code Availability**: in a public GitHub repo
- [x] **License**: Apache 2.0
- [x] **Production Use**
- [x] **Insights**: #55
- [x] **Packaging**: score correct, could improve discoverability  #47 
- [x] **Deployment**: not applicable, so opted out

**Comment by idg10** [comment]
#33 tracks the *Production Use* progress
